name: "Install-dependencies-and-plottr"
description: "Install plottr and its dependencies"
runs:
  using: "composite"
  steps:
    - name: Install-dependencies
      run: uv sync --extra pyqt5 --group test
      shell: bash
